adding redirect hooks
chrisreedio/socialment pull request #40
Opened 2024-01-30 15:05 UTC by rupadana

this hooks used to modify socialite scope or other before redirected

```php
public function boot(): void
{
    Socialment::redirect(function(AbstractProvider $provider) {
        return $provider->setScopes([
            'repo','read:user'
        ]);
    });
}
```

2024-01-30 19:00 UTC, chrisreedio commented
@rupadana Can you explain why this is needed?

I'm not seeing a big use case personally.

2024-01-30 23:39 UTC, chrisreedio commented
Bringing over some notes from Discord:

```php
->plugins([
    \ChrisReedIO\Socialment\SocialmentPlugin::make()
        ->registerProvider('azure', 'fab-windows', 'Azure'),
        ->registerProvider('github', 'fab-github', 'Github', scopes: ['repo', 'read:user']),
])
```

Something like this would allow for differing scopes per provider, per panel.

Need some additional thoughts for multi-tenancy.

2024-02-05 13:41 UTC, rupadana commented
@chrisreedio please review it again

2024-05-03 21:54 UTC, chrisreedio requested changes

2024-05-03 21:54 UTC, chrisreedio commented on src/Http/Controllers/SocialmentController.php
> +        return Socialment::resolveRedirectCallback($provider, Socialite::driver($provider))->redirect();
Would this not need to also be used in the other redirect handlers?

2024-05-03 21:54 UTC, chrisreedio commented on src/Socialment.php
> +        return $this->providers[$driver];
This has been added by another PR in a slightly more enhanced fashion. Please pull and revise.

2024-05-04 01:54 UTC, chrisreedio commented
This has been implemented by #58

2024-05-04 01:54 UTC, closed without merging