feat: add ability to customize model and table name
chrisreedio/socialment pull request #70
Opened 2024-11-01 14:33 UTC by leek

2025-01-28 06:37 UTC, chrisreedio requested changes
I think everything but that one line looks good.

2025-01-28 06:37 UTC, chrisreedio commented on config/socialment.php
> +        'user' => \App\Model\User::class,
Not sure this needed to change. Since the package doesn't ship with a user model I believe this will fail?

2025-01-28 13:30 UTC, leek commented on config/socialment.php
> +        'user' => \App\Model\User::class,
```suggestion
        'user' => '\App\Models\User',
```

2025-01-28 13:31 UTC, leek commented
> I think everything but that one line looks good.

Fixed 👍

2025-02-19 18:24 UTC, pepperfm commented on src/Models/ConnectedAccount.php
> +        $config = Config::get('socialment');
May I suggest the idea from my [PR](https://github.com/chrisreedio/socialment/pull/65) here?
To use helpers instead of facades (explanation in the discussion)

In this commit, we have two different coding styles: the config facade + helper combination, which seems a bit overengineered

Since you're not opposed to using helpers (as discussed in the method below), I suggest we apply the same approach here, above, and use it as well

2025-02-19 18:27 UTC, pepperfm commented on src/Models/ConnectedAccount.php
> +        $config = Config::get('socialment');
@chrisreedio Don’t mind me, I’m just watching your every move... in the most non-creepy way possible! :grin:

2025-09-17 16:17 UTC, leek commented
@chrisreedio This is a super small PR that is fully backwards compatible. Can we get this one merged?

2025-09-17 18:20 UTC, chrisreedio reviewed
If we're allowing customization of the Connected Account model, should we just depend on that model to set the table name?

Might make the migration kind of "weird" but would prevent any issues of setting the table name to one thing in the config and the model having a different one? 

Still thinking about this a bit.

2025-09-17 18:30 UTC, leek commented
> If we're allowing customization of the Connected Account model, should we just depend on that model to set the table name?
> 
> Might make the migration kind of "weird" but would prevent any issues of setting the table name to one thing in the config and the model having a different one?
> 
> Still thinking about this a bit.

This PR allows you to override the model or just override the table name. This is how Spatie packages handle this ([example](https://github.com/spatie/laravel-activitylog/blob/main/config/activitylog.php#L38)).

~~I just want the table name to be plural to follow Laravel standards without having to use a fork.~~

/cc @chrisreedio

2025-09-17 18:32 UTC, chrisreedio commented
> > If we're allowing customization of the Connected Account model, should we just depend on that model to set the table name?
> > 
> > Might make the migration kind of "weird" but would prevent any issues of setting the table name to one thing in the config and the model having a different one?
> > 
> > Still thinking about this a bit.
> 
> This PR allows you to override the model or just override the table name. This is how Spatie packages handle this.
> 
> I just want the table name to be plural to follow Laravel standards without having to use a fork.
> 
> /cc @chrisreedio 

Before this PR the table name was already plural?

2025-09-17 18:34 UTC, leek commented
> Before this PR the table name was already plural?

Oh weird. I could have sworn it used to create `connected_account`. My mistake.

2026-03-05 18:21 UTC, closed without merging